kind: pipeline
type: exec
name: win_build

platform:
  os: windows
  arch: amd64

clone:
  depth: 1

trigger:
  branch:
  - server-gui-win

steps:
- name: build
  commands:
  - .\install\pip_build_win.bat
  
- name: run_pyinstaller
  commands:
  - .\install\pyinstaller_win.bat

- name: copy_hack
  commands:
  - 'cp install/dist/tts_server_wrapper.exe C:\Drone\tts-server.exe'
